### PR TITLE
Fixed an issue with internalization messages locale filter

### PR DESCRIPTION
**Pull request by StanislavFedorov**
https://github.com/BroadleafCommerce/QA/issues/3606

### CODE REVIEW

**Comment by Jerry77oz** [comment]
@StanislavFedorov the fix for the actual filter UI is much better now but we are still hitting a small issue. We now have the filter that uses `contains`

image

But setting `en` in the field returns no results. It looks like it is doing an exact match since if I enter in `en_US` it does bring back the messages that have that locale.

**Review by Jerry77oz — CHANGES_REQUESTED** [review]
See comment in conversation.

**Comment by StanislavFedorov** [comment]
@Jerry77oz 
I have solved this issue in other way. Via "is in" filter (but not "contains"). I have reworked a little bit both backend and frontend code.

**Review by Jerry77oz — APPROVED** [review]

**Comment by Jerry77oz** [comment]
Looks good!

**Pull request merged**
