### PR TITLE
 Fix for filter builder throws error on new filter adding

### PR DESCRIPTION
**Pull request by oleksiimiroshnyk**
- Fix for filter builder throws error on new filter adding

Fixes: BroadleafCommerce/QA#5026

### CODE REVIEW

**Review by StanislavFedorov — APPROVED** [review]

**Comment by MarekB01** [comment]
Seems we are ready to merge this one @riteshadhikari17

**Review by riteshadhikari17 — CHANGES_REQUESTED** [review]
I see some commented codes: line 320 and 333. Can we get rid of them?

**Comment by oleksiimiroshnyk** [comment]
> I see some commented codes: line 320 and 333. Can we get rid of them?

done

**Comment by MarekB01** [comment]
I retested this solution with this workflow:
Login to Admin page with valid account
Go to Settings > Roles
Click Add Admin Role
Reach Permission Filter > Apply any filter > Close pop-up
Click on Filter > Delete the filter
And everything works as expected

**Review by riteshadhikari17 — APPROVED** [review]

**Pull request merged**
