### PR TITLE
Fixed MVEL internal quotes escaping

### PR DESCRIPTION
**Pull request by jetchegoyen**
BroadleafCommerce/QA#4108
Fixed MVEL internal quotes escaping

### CODE REVIEW

**Comment by danielcolgrove** [comment]
Setup a product with a quoted name and the rendering of the rule builder wasn't correct.  It showed the escaped value.  Product was

Insanity Sauce 8" "hi-top" bottle

Screen Shot 2020-07-14 at 7 23 02 PM

**Comment by oleksiimiroshnyk** [comment]
there are couple of issues:
1. Reported by the client, MVEL doesn't allow unbalanced quotes. Like if you choose to wrap string elements of the "array" to be double quote - " then you have to have even number of those quotes, and doesn't matter escape you them or not.
So it will allow you - some"thing", but will not allow you some"thing, but will allow you some'thing because we use double quote to wrap string elements in array.

The only solution I found is to replace actual string elements to variables and assign string values to those variables.
For example:
Collection.intersect(orderItem.name,["blah-blah","bad\"string"]).size>0 -> will be changed to:
Collection.intersect(orderItem.name,[var1,var2]).size>0 , where var1=blah-blah, var2=bad\"string

2. Another issue is that when you have added some"thing" to rule builder and want to add more products, for example just Sudden Death after save, reload, save etc you will end up that value printed will be some"thing Sudden Death .
Closing quote will be missing, and after some save this corrupted string also will be persisted to DB.
This is because we have a regexp that is too aggressive for replacement.

**Comment by oleksiimiroshnyk** [comment]
@jetchegoyen I pushed a fix.
See my prev. comment of the reasons I did such fix

this requires careful testing as some cases might be missing

**Comment by oleksiimiroshnyk** [comment]
looks like if we decide to go with this solution, it should support quite a lot of different cases - now it fails on tests, because it doesn't expect [eval("aaa","bbb", eval("ddd,"ddd"))] contains eval("sss","yyy")

**Comment by danielcolgrove** [comment]
Can you update the tests so they will pass?

**Comment by oleksiimiroshnyk** [comment]
ok, seems I missed the working case:
expression:
CollectionUtils.intersection(orderItem.?name,[\"5\\u0022 wrench\"]).size()>0
works
EDIT: looks like formatting problems: you need 2 slashes before u0022

so my fix can be rolled back for the AbstractBaseController

fix for blc_admin.js probably needs to be revisited. and myabe that's the place BLCAdmin.unescapeString where we can replace u0022 with quotes ?

**Comment by jetchegoyen** [comment]
just tested with **Insanity Sauce 8" "hi-top" bottle** and so far is working fine.
I updated `ruleBuilder.html` template replacing the escaped string, and looks good on the ui.

`data-data=${#strings.replace(field.dataWrapper.serialize(), '\u0022', '&quot;')},`

**Pull request merged**
