### PR TITLE
Fixes the Spring Web Security vulnerability

### PR DESCRIPTION
**Pull request by KatrukOV**
**A Brief Overview**
Updated versions of spring, spock, jackson, groovy, logback, commons-*, dependency-check-maven, junit-vintage-engine, easymock, solr-solrj, byte-buddy, mvel2, zookeeper, zookeeper-jute

**Link to QA issue**
[QA-5212](https://github.com/BroadleafCommerce/QA/issues/5212)

### CODE REVIEW

**Review by oleksiimiroshnyk — APPROVED** [review]

**Comment by riteshadhikari17** [comment]
This is causing bunch of test failures
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CatalogTest>AbstractTestNGSpringContextTests.run:154->testCatalog:140
[ERROR]   FutureCreditOfferTest>AbstractTestNGSpringContextTests.run:154->testFutureCreditAllOfferTypes:196 » IllegalArgument attempt to create merge event with null entity
[ERROR]   FutureCreditOfferTest>AbstractTestNGSpringContextTests.run:154->testFutureCreditAndOrderDiscountOrderAndOrderItemOffers:164 » IllegalArgument attempt to create merge event with null entity
[ERROR]   FutureCreditOfferTest>AbstractTestNGSpringContextTests.run:154->testFutureCreditAndOrderDiscountPercentOffOffers:136 » IllegalArgument attempt to create merge event with null entity
[ERROR]   FutureCreditOfferTest>AbstractTestNGSpringContextTests.run:154->testTwoFutureCreditPercentOffOffers:108 » IllegalArgument attempt to create merge event with null entity
[ERROR]   OfferAuditTest>AbstractTestNGSpringContextTests.run:154->testMinimumDaysPerUsageAudit:110 » IllegalArgument attempt to create merge event with null entity
[ERROR]   OfferTest>AbstractTestNGSpringContextTests.run:154->testBOGOAmountOffCombination:188 » IllegalArgument attempt to create merge event with null entity
[ERROR]   OfferTest>AbstractTestNGSpringContextTests.run:154->testBOGOCombination:169 » IllegalArgument attempt to create merge event with null entity
[ERROR]   OfferTest>AbstractTestNGSpringContextTests.run:154->testOfferUsedForPricing:263 » IllegalArgument attempt to create merge event with null entity
[ERROR]   OfferTest>AbstractTestNGSpringContextTests.run:154->testPercentOffOfferWithItemMinPriceQuantityReduction:242 » IllegalArgument attempt to create merge event with null entity
[ERROR]   OfferTest>AbstractTestNGSpringContextTests.run:154->testPercentOffOfferWithItemMinPriceSecondEvaluation:224 » IllegalArgument attempt to create merge event with null entity
[ERROR]   OfferTest>AbstractTestNGSpringContextTests.run:154->testPercentOffOfferWithScaleGreaterThanTwo:209 » IllegalArgument attempt to create merge event with null entity
[ERROR]   OfferTest>AbstractTestNGSpringContextTests.run:154->testThreePercentOffOffers:130 » IllegalArgument attempt to create merge event with null entity
[ERROR]   OfferTest>AbstractTestNGSpringContextTests.run:154->testTwoPercentOffOffers:150 » IllegalArgument attempt to create merge event with null entity
[INFO] 
[ERROR] Tests run: 160, Failures: 14, Errors: 0, Skipped: 25
```

**Comment by riteshadhikari17** [comment]
@KatrukOV NVM this is coming from develop branch. Looks like https://github.com/BroadleafCommerce/BroadleafCommerce/pull/2980 broke something. Please fix the develop branch and I'll trigger these PR again.

**Comment by oleksiimiroshnyk** [comment]
@riteshadhikari17 locally tests are good in 7.0 branch as well as in this branch

[INFO] Tests run: 160, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 52.02 s -- in TestSuite
[INFO] 
[INFO] Results:
[INFO]
[INFO] Tests run: 160, Failures: 0, Errors: 0, Skipped: 0

they are good from maven and from IDE, so I suspect that jenkins for whatever reason gives false positive results.. I don't remember those tests to be flaky, can you please try it locally just to check if this can be reproduced somewhere except jenkins...?

**Comment by riteshadhikari17** [comment]
@OrestKatruk if everything's passes for u, u can go ahead and merge this PR. I have opened[ separate ticket](https://github.com/BroadleafCommerce/QA/issues/5231) to investigate test failures.

**Review by riteshadhikari17 — APPROVED** [review]

**Pull request merged**
