### PR TITLE
When creating a new Media value, make sure it's added to the parent

### PR DESCRIPTION
**Pull request by smmckay**
Addresses #1366

### CODE REVIEW

**Comment by bpolster** [comment]
Thanks for the pull request.    Assigning to @jefffischer to take a closer look.   

@smmckay - you are getting into blc-ninja territory here.   :)

**Comment by jefffischer** [comment]
@smmckay - can you describe the problem you encountered that the pull request resolved, including before and after behavior.

**Comment by jefffischer** [comment]
@smmckay - sorry, ignore. I see that you reference #1366 in your comment.

**Comment by jefffischer** [comment]
The particular solution you propose would interfere with some of the operations of our enterprise module. I understand that you still need a resolution for updating the collection cache state, but we'll need to devise another approach. We'll continue to track this on the #1366 issue you created. I'm closing this pull request for now.

**Pull request closed without merging**
