### PR TITLE
Cannot create a profile based on master profile

### PR DESCRIPTION
**Pull request by StanislavFedorov**
https://github.com/BroadleafCommerce/QA/issues/4209

### CODE REVIEW

**Comment by riteshadhikari17** [comment]
This change was fix for this issue https://github.com/BroadleafCommerce/QA/issues/4035. Need to find a solution that works for both cases.

**Comment by StanislavFedorov** [comment]
@riteshadhikari17 
Added Unique Constraint for "NAME" and "SITE_DISC". Should work in both cases

**Comment by riteshadhikari17** [comment]
There is a test failure. Happens locally as well. Here is the error
```
Unable to create unique key constraint (NAME, SITE_DISC) on table BLC_FLD_GROUP: database column 'SITE_DISC' not found. Make sure that you use the correct column name which depends on the naming strategy in use (it may not be the same as the property name in the entity, especially for relational types)
```

**Comment by StanislavFedorov** [comment]
@riteshadhikari17 
Hmm...
"SITE_DISC" is the column from `SiteDiscriminatorImpl `class
For me this works locally. What is the difference with this enviroment?

**Comment by riteshadhikari17** [comment]
It is running java 8. I Don't get error when I switch to java 11

**Comment by StanislavFedorov** [comment]
I am on java 8
image

**Comment by riteshadhikari17** [comment]
Are you running "mvn test"?

**Pull request closed without merging**
