### PR TITLE
QA-3354 Product groups/add-ons not working correctly

### PR DESCRIPTION
**Pull request by oleksiimiroshnyk**
BroadleafCommerce/QA#3354
Apply typed enity filter for product more correctly

### CODE REVIEW

**Comment by ccs19** [comment]
Looks like add-ons are showing up correctly now. However, I noticed that they are not showing up under "All Products". The count accurately reflects Base + Add On products, but Add Ons are not loading and showing as `(No records found)`. See attached image.
image

**Comment by ccs19** [comment]
There is also another bug regarding Product Groups. When using rule based groups, e.g. Products in a category, add-ons don't seem to be included in the results. Base products work fine with the rule based product groups.

**Comment by oleksiimiroshnyk** [comment]
@ccs19 can't reproduce issue with All Products.
allproducts

Not really familiar with Product Groups, can please give me an overview and steps to reproduce?

**Comment by ccs19** [comment]
Sure.

Go to Catalog -> Product Groups -> Add a new group -> Select Rule Based -> Product Category (is in) A category

Then attach that product group to a product as an add-on.

**Pull request merged**
