### PR TITLE
Test to ensure that product options are correctly sorted by displayOrder

### PR DESCRIPTION
**Pull request by ncrum**
This pertains to issue BroadleafCommerce/QA#419.
While testing the solution to this issue I found a small oversight where the method was returning productOptions list instead of the sorted list it had just created. 

Here are my steps:
1. Create ProductSpec.groovy to test product options being returned sorted by displayOrder
2. Test failed
3. Changed return value within getProductOptionXrefs() from 'productOptions' to 'sorted'
4. Test succeeded

@phillipuniverse - please take a look and let me know what you think

### CODE REVIEW

**Comment by ncrum** [comment]
@phillipuniverse - Knowing spock testing makes testing java a million times easier. I understand why you want people to learn it.

**Comment by phillipuniverse** [comment]
A+ for finding that bug!

Can you add 1 more test: test what happens if you don't set a displayOrder, meaning that it's null? I think that what should happen (according to how I am sorting it) is that it will appear first in the list, followed by all the ones that have specified a `displayOrder`.

**Comment by ncrum** [comment]
done @phillipuniverse

**Comment by bpolster** [comment]
@phillipuniverse - In BLC, we are trying to consistently treat a null as displaying last

**Comment by ncrum** [comment]
From my testing I simply never set a displayOrder for one product option. The result was that option displayed first. The 'displayOrder' instance variable is an Integer. Which defaults it to 'null'. 
This could be fixed to display null last if we use `ObjectUtils.compare(final T c1, final T c2, final boolean nullGreater)` in getProductOptionXrefs() as the following:
```java
public List<ProductOptionXref> getProductOptionXrefs() {
    List<ProductOptionXref> sorted = new ArrayList<ProductOptionXref>(productOptions);
    Collections.sort(sorted, new Comparator<ProductOptionXref>() {

        @Override
        public int compare(ProductOptionXref o1, ProductOptionXref o2) {
            return ObjectUtils.compare(o1.getProductOption().getDisplayOrder(), o2.getProductOption().getDisplayOrder(), true);
        }
            
    });
    return sorted;
}
```

@bpolster should I branch and add an issue for this change?

**Comment by bpolster** [comment]
In this case, tie your commit to this same issue #1289 and reference BroadleafCommerce/QA#419

**Comment by ncrum** [comment]
done

**Comment by ncrum** [comment]
I went ahead and pushed the change to develop since this branch was already merged

**Pull request merged**
