### PR TITLE
Added Spring Mobile module to detect request device and make available for RuleBuilders

### PR DESCRIPTION
**Pull request by nathandmoore**
BroadleafCommerce/QA#2939

### CODE REVIEW

**Comment by nathandmoore** [comment]
@jfleschler updated

**Comment by phillipuniverse** [comment]
@nathandmoore @jfleschler just a heads up you _cannot_ use `@Resource` in anything that the servlet knows about with Spring Boot. This goes for `Filter`, `ServletContextInitializer`, etc. The way that the filters get registered is different and `@Resource` makes it look for a JNDI resource instead. It only manifests itself when you deploy to an external version of Tomcat with an error message about not finding a resource. See BroadleafCommerce/BroadleafCommercePrivate#958 where we actually went through and modified every filter in Broadleaf to use `@Autowired` instead so that the servlet API doesn't get confused.

I fixed this in 2524a46ff6 but wanted to make sure you guys were explicitly aware of that.

**Comment by droyop** [comment]
Hi @phillipuniverse 

We think we're facing this problem in our application while deploying the API to an standalone tomcat in GCE. We are on 5.2.2-GA

```
29-Jan-2018 00:21:47.083 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter apiCustomerStateFilter
 javax.naming.NameNotFoundException: Name [blCustomerService] is not bound in this Context. Unable to find [blCustomerService].
        at org.apache.naming.NamingContext.lookup(NamingContext.java:817)
        at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
        at org.apache.catalina.core.DefaultInstanceManager.lookupFieldResource(DefaultInstanceManager.java:552)
        at org.apache.catalina.core.DefaultInstanceManager.processAnnotations(DefaultInstanceManager.java:452)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:142)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:134)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4591)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

29-Jan-2018 00:21:47.090 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter blSessionFixationProtectionFilter
 javax.naming.NameNotFoundException: Name [blSessionFixationEncryptionModule] is not bound in this Context. Unable to find [blSessionFixationEncryptionModule].
        at org.apache.naming.NamingContext.lookup(NamingContext.java:817)
        at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
        at org.apache.catalina.core.DefaultInstanceManager.lookupFieldResource(DefaultInstanceManager.java:552)
        at org.apache.catalina.core.DefaultInstanceManager.processAnnotations(DefaultInstanceManager.java:452)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:142)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:134)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4591)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Ultimately the API security config ends up here...

```
public class RestApiCustomerStateFilter extends GenericFilterBean implements Ordered {
    protected static final Log LOG = LogFactory.getLog(RestApiCustomerStateFilter.class);
    @Resource(
        name = "blCustomerService"
    )
    protected CustomerService customerService;
```

**Comment by phillipuniverse** [comment]
@droyop there were a few other areas that we missed in 2524a46, they have been resolved in #1771. You can verify with the latest 5.2.3-SNAPSHOT.

**Comment by droyop** [comment]
Hi, with the changes from @Resource to @Autowire everything works like a charm.

Thanks!

**Pull request merged**
