### PR TITLE
Fix to remove excessive calls to server when changing catalog/profile in admin

### PR DESCRIPTION
**Pull request by oleksiimiroshnyk**
BroadleafCommerce/QA#3761
fix for not refreshing page

### CODE REVIEW

**Review by nathandmoore — CHANGES_REQUESTED** [review]
@oleksiimiroshnyk Won't this break wherever `addUrlParam` is called and the caller expects the location to change? The function did what it did intentionally.

I would expect that we'd make a new function that has the new desired behavior and make sure to document the original one correctly. Then, update the `multitenant.js` where we use `BLC.addUrlParam` twice with the new function since that seems to be what was causing the issue described.

**Comment by oleksiimiroshnyk** [comment]
@nathandmoore do you know who/what logic expects that adding url param will refresh a page?
I was thinking who and why can expect that and didn't found an answer, I tested the logic I could and it worked. Do you know if something is broken with this fix ?
Because to me it sounds like bad original impl.

**Comment by nathandmoore** [comment]
@oleksiimiroshnyk The locale selector uses it, and we don't know what clients are using it in their code expecting the original behavior. Changing the fundamental behavior of the method could introduce bugs for them. We shouldn't do that in a patch release.

**Comment by Vitalij-Voronkoff** [comment]
@nathandmoore solution reworked.

**Review by nathandmoore — APPROVED** [review]

**Pull request merged**
