### PR TITLE
Removed StateImpl bean from context

### PR DESCRIPTION
**Pull request by MarekB01**
https://github.com/BroadleafCommerce/QA/issues/4737

I changed persistence-profile.xml and bl-profile-applicationContext-entity.xml so when program reads context it does not create a StateImpl bean

### CODE REVIEW

**Comment by danielcolgrove** [comment]
@riteshadhikari17 @MarekB01 If the StateImpl is gone, we may need data migration scripts.

**Comment by MarekB01** [comment]
> @riteshadhikari17 @MarekB01 If the StateImpl is gone, we may need data migration scripts.
Yeah, I told about it Ritesh. We need to remove BLC_STATE column from database

**Comment by riteshadhikari17** [comment]
@danielcolgrove  It was actually removed in https://github.com/BroadleafCommerce/BroadleafCommerce/pull/2548. These are the references that were missed.

**Comment by riteshadhikari17** [comment]
@MarekB01 Do you mean BLC_STATE table? You will have to remove these https://github.com/BroadleafCommerce/BroadleafCommerce/blob/9cf3f7fab00acc1568cbcee28d5914f44503969d/core/broadleaf-profile/src/main/resources/config/bc/sql/demo/load_code_tables.sql#L284

**Review by oleksiimiroshnyk — APPROVED** [review]

**Review by riteshadhikari17 — CHANGES_REQUESTED** [review]
Remove the insert statements from load_code_tables as well

**Review by riteshadhikari17 — APPROVED** [review]

**Pull request merged**
